-- TASK-032 verification: CRA engine v2 -- policy structure, publish-time
-- validation, immutability, privileges and the app.evaluate_cra evaluator.
--
-- The 24 casebook cases below are the acceptance oracle. The jsonb literal is
-- byte-identical to apps/web/tests/fixtures/cra-casebook-v1.json (the
-- orchestrator's casebook-v1.json) -- a unit test in
-- apps/web/tests/domain/cra-engine.test.ts fails if the two ever diverge. It
-- was generated by embedding the file's exact contents between dollar-quote
-- tags (no re-serialisation); regenerate it the same way, never by hand.
-- The policy under test is the seeded CRA Template v1 DRAFT, published in the
-- "EU Payments Demo Ltd." tenant by supabase/seed.sql.
--
-- Run in a single psql session after 000-local-auth-shim.sql, all migrations
-- and supabase/seed.sql. See supabase/tests/README.md.

\set ON_ERROR_STOP on

begin;

create or replace function pg_temp.assert(p_condition boolean, p_message text)
returns void language plpgsql as $$
begin
  if not p_condition then
    raise exception 'ASSERTION FAILED: %', p_message;
  end if;
  raise notice 'ok - %', p_message;
end;
$$;

-- Runs a statement and returns 'OK' or the SQLSTATE it raised.
create or replace function pg_temp.sqlstate_of(p_sql text)
returns text language plpgsql as $$
begin
  execute p_sql;
  return 'OK';
exception when others then
  return sqlstate;
end;
$$;

-- Copies the seeded CRA policy into a new DRAFT cra_v2 version (of any
-- tenant) so a test can mutate one thing and try to publish it.
create or replace function pg_temp.copy_cra(p_tenant uuid, p_version_number int)
returns uuid language plpgsql as $$
declare
  v_new uuid := gen_random_uuid();
  v_src constant uuid := '20000000-0000-0000-0000-000000000020';
begin
  insert into public.policy_versions (id, tenant_id, version_number, status, created_by, engine_kind, label, missing_factor_points)
  select v_new, p_tenant, p_version_number, 'draft', '00000000-0000-0000-0000-000000000002', 'cra_v2', label, missing_factor_points
  from public.policy_versions where id = v_src;
  insert into public.policy_categories (tenant_id, policy_version_id, key, label, weight, position)
  select p_tenant, v_new, key, label, weight, position from public.policy_categories where policy_version_id = v_src;
  insert into public.policy_category_factors (tenant_id, policy_version_id, category_key, factor_key, weight, position, points)
  select p_tenant, v_new, category_key, factor_key, weight, position, points from public.policy_category_factors where policy_version_id = v_src;
  insert into public.policy_overrides (tenant_id, policy_version_id, code, position, fact_key, match_values, effect, actions, approvals)
  select p_tenant, v_new, code, position, fact_key, match_values, effect, actions, approvals from public.policy_overrides where policy_version_id = v_src;
  insert into public.policy_cra_bands (tenant_id, policy_version_id, band, min_score, max_score, max_inclusive, dd_level, review_months, actions, approvals)
  select p_tenant, v_new, band, min_score, max_score, max_inclusive, dd_level, review_months, actions, approvals from public.policy_cra_bands where policy_version_id = v_src;
  return v_new;
end;
$$;

-- Tries to publish; a failure is rolled back (inner block) and its SQLSTATE returned.
create or replace function pg_temp.try_publish(p_version uuid)
returns text language plpgsql as $$
begin
  update public.policy_versions
  set status = 'published', effective_from = now(), published_at = now(),
      published_by = '00000000-0000-0000-0000-000000000002'
  where id = p_version;
  return 'OK';
exception when others then
  return sqlstate;
end;
$$;

-- Fixtures: demo tenant D = ...0004, seeded CRA policy P = 2000...0020,
-- Meridian M = ...0003 with its weighted_v1 policy W = 2000...0010.
create temp table cra_casebook (c jsonb) on commit drop;
insert into cra_casebook
select value from jsonb_array_elements($casebook$[
 {
  "id": "CB-01",
  "title": "Clean e-commerce customer at onboarding (face-to-face, bank transfer)",
  "source": "P1.7 low-risk path",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-02",
  "title": "Gambling purpose, card payment, non-face-to-face, onboarding",
  "source": "P1.7",
  "facts": {
   "purpose": "gambling",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "card",
   "product_type": "closed_loop",
   "channel": "non_face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 17.5,
   "category_scores": {
    "customer": 15.0,
    "geography": 0.0,
    "product_payment": 30.0,
    "channel": 100.0,
    "transactions": 0.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_MEDIUM",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_MEDIUM",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-03",
  "title": "Cash payment, cash-intensive occupation, higher-risk nationality",
  "source": "P1.7",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "cash_intensive",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "higher",
   "sow_country_risk": "standard",
   "payment_method": "cash",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 12.5,
   "category_scores": {
    "customer": 10.0,
    "geography": 15.0,
    "product_payment": 60.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_MEDIUM",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_MEDIUM",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_HIGH",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-04",
  "title": "Worst onboarding profile without overrides (transactions not yet observed)",
  "source": "P1.7 — shows Q1 impact",
  "facts": {
   "purpose": "multipurpose",
   "employment_status": "unemployed",
   "occupation_risk": "high_risk",
   "adverse_media_non_material": "multiple",
   "prior_str": "one_or_more",
   "residence_country_risk": "high_risk_third_country",
   "nationality_risk": "high_risk_third_country",
   "sow_country_risk": "high_risk_third_country",
   "payment_method": "cash",
   "product_type": "open_loop",
   "channel": "non_face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 55.0,
   "category_scores": {
    "customer": 100.0,
    "geography": 100.0,
    "product_payment": 100.0,
    "channel": 100.0,
    "transactions": 0.0
   },
   "band": "MEDIUM",
   "dd_level": "CDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE"
   ],
   "review_months": 24,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_HIGH",
    "FACTOR_EMPLOYMENT_STATUS_HIGH",
    "FACTOR_OCCUPATION_RISK_HIGH",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_HIGH",
    "FACTOR_PRIOR_STR_HIGH",
    "FACTOR_RESIDENCE_COUNTRY_RISK_HIGH",
    "FACTOR_NATIONALITY_RISK_HIGH",
    "FACTOR_SOW_COUNTRY_RISK_HIGH",
    "FACTOR_PAYMENT_METHOD_HIGH",
    "FACTOR_PRODUCT_TYPE_HIGH",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_MEDIUM",
    "DD_CDD"
   ]
  }
 },
 {
  "id": "CB-05",
  "title": "Same as CB-04 after transactions observed: above affordability, significant behaviour change, high-value tx",
  "source": "P2.8 ongoing CRA",
  "facts": {
   "purpose": "multipurpose",
   "employment_status": "unemployed",
   "occupation_risk": "high_risk",
   "adverse_media_non_material": "multiple",
   "prior_str": "one_or_more",
   "residence_country_risk": "high_risk_third_country",
   "nationality_risk": "high_risk_third_country",
   "sow_country_risk": "high_risk_third_country",
   "payment_method": "cash",
   "product_type": "open_loop",
   "channel": "non_face_to_face",
   "affordability": "above_limit",
   "behaviour_change": "significant",
   "high_value_transactions": "yes",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 100.0,
   "category_scores": {
    "customer": 100.0,
    "geography": 100.0,
    "product_payment": 100.0,
    "channel": 100.0,
    "transactions": 100.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_HIGH",
    "FACTOR_EMPLOYMENT_STATUS_HIGH",
    "FACTOR_OCCUPATION_RISK_HIGH",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_HIGH",
    "FACTOR_PRIOR_STR_HIGH",
    "FACTOR_RESIDENCE_COUNTRY_RISK_HIGH",
    "FACTOR_NATIONALITY_RISK_HIGH",
    "FACTOR_SOW_COUNTRY_RISK_HIGH",
    "FACTOR_PAYMENT_METHOD_HIGH",
    "FACTOR_PRODUCT_TYPE_HIGH",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_HIGH",
    "FACTOR_BEHAVIOUR_CHANGE_HIGH",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_HIGH",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-06",
  "title": "Ongoing review: clean profile but above affordability limit",
  "source": "P2.2c / P2.8",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "above_limit",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 22.5,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 50.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_HIGH",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-07",
  "title": "Ongoing review: gambling, card, non-F2F, near affordability limit, moderate behaviour change",
  "source": "P2.8",
  "facts": {
   "purpose": "gambling",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "card",
   "product_type": "closed_loop",
   "channel": "non_face_to_face",
   "affordability": "near_limit",
   "behaviour_change": "moderate",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 35.5,
   "category_scores": {
    "customer": 15.0,
    "geography": 0.0,
    "product_payment": 30.0,
    "channel": 100.0,
    "transactions": 40.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_MEDIUM",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_MEDIUM",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_MEDIUM",
    "FACTOR_BEHAVIOUR_CHANGE_MEDIUM",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-08",
  "title": "Ongoing review lands in MEDIUM: gambling, card, non-F2F, above limit + moderate change",
  "source": "P2.8",
  "facts": {
   "purpose": "gambling",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "card",
   "product_type": "closed_loop",
   "channel": "non_face_to_face",
   "affordability": "above_limit",
   "behaviour_change": "moderate",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 46.75,
   "category_scores": {
    "customer": 15.0,
    "geography": 0.0,
    "product_payment": 30.0,
    "channel": 100.0,
    "transactions": 65.0
   },
   "band": "MEDIUM",
   "dd_level": "CDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE"
   ],
   "review_months": 24,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_MEDIUM",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_MEDIUM",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_HIGH",
    "FACTOR_BEHAVIOUR_CHANGE_MEDIUM",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_MEDIUM",
    "DD_CDD"
   ]
  }
 },
 {
  "id": "CB-09",
  "title": "Confirmed sanctions match on a clean profile",
  "source": "P1.3 / P3.3",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "confirmed",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REJECT",
   "overrides_hit": [
    "OVR_SANCTIONS_CONFIRMED"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS",
    "FREEZE_FUNDS_AND_BLOCK_IF_EXISTING",
    "REJECT_IF_PROSPECT",
    "REPORT_TO_MLRO"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_SANCTIONS_CONFIRMED",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-10",
  "title": "Inconclusive (partial) sanctions match",
  "source": "P1.3 partial match",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "inconclusive",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [
    "OVR_SANCTIONS_INCONCLUSIVE"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS",
    "BLOCK_PENDING_MANUAL_REVIEW"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_SANCTIONS_INCONCLUSIVE",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-11",
  "title": "PEP confirmed by screening",
  "source": "P1.5",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "confirmed",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [
    "OVR_PEP"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_PEP",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-12",
  "title": "PEP self-declared in SOW questionnaire",
  "source": "P1.6",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "self_declared",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [
    "OVR_PEP"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_PEP",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-13",
  "title": "Material adverse media (AML/CFT conviction)",
  "source": "P1.4",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "material",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [
    "OVR_ADVERSE_MEDIA_MATERIAL"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS",
    "REPORT_TO_MLRO"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_ADVERSE_MEDIA_MATERIAL",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-14",
  "title": "Potential material adverse media (under investigation)",
  "source": "P1.4",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "potential",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [
    "OVR_ADVERSE_MEDIA_POTENTIAL"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_ADVERSE_MEDIA_POTENTIAL",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-15",
  "title": "High-net-worth individual",
  "source": "P1.7 condition",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": true,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [
    "OVR_HNWI"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_HNWI",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-16",
  "title": "Declared active links to blacklisted country",
  "source": "P1.2 / P3.5",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": true
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REJECT",
   "overrides_hit": [
    "OVR_BLACKLISTED_COUNTRY"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS",
    "REJECT_OR_TERMINATE",
    "REPORT_TO_MLRO"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_BLACKLISTED_COUNTRY",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-17",
  "title": "Multiple overrides: PEP + confirmed sanctions (reject wins)",
  "source": "precedence",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "confirmed",
   "pep_status": "confirmed",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REJECT",
   "overrides_hit": [
    "OVR_SANCTIONS_CONFIRMED",
    "OVR_PEP"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS",
    "FREEZE_FUNDS_AND_BLOCK_IF_EXISTING",
    "REJECT_IF_PROSPECT",
    "REPORT_TO_MLRO"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_SANCTIONS_CONFIRMED",
    "OVR_PEP",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-24",
  "title": "Two reject overrides sharing an action: material adverse media + blacklisted country (REPORT_TO_MLRO listed once)",
  "source": "override de-duplication",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "material",
   "hnwi": false,
   "blacklisted_country_link": true
  },
  "expected": {
   "overall_score": 0.0,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REJECT",
   "overrides_hit": [
    "OVR_BLACKLISTED_COUNTRY",
    "OVR_ADVERSE_MEDIA_MATERIAL"
   ],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS",
    "REJECT_OR_TERMINATE",
    "REPORT_TO_MLRO"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "OVR_BLACKLISTED_COUNTRY",
    "OVR_ADVERSE_MEDIA_MATERIAL",
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-18",
  "title": "Non-material adverse media only (not an override)",
  "source": "P1.4 non-material",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "single",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 1.5,
   "category_scores": {
    "customer": 7.5,
    "geography": 0.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_MEDIUM",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-19",
  "title": "Missing SOW-derived facts (occupation, employment, SOW country) at onboarding",
  "source": "data quality",
  "facts": {
   "purpose": "ecommerce",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 5.5,
   "category_scores": {
    "customer": 20.0,
    "geography": 15.0,
    "product_payment": 0.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [
    "employment_status",
    "occupation_risk",
    "sow_country_risk"
   ],
   "reason_codes": [
    "FACTOR_PURPOSE_LOW",
    "DATA_MISSING_EMPLOYMENT_STATUS",
    "DATA_MISSING_OCCUPATION_RISK",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "DATA_MISSING_SOW_COUNTRY_RISK",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-20",
  "title": "Invalid value supplied for payment_method",
  "source": "validation",
  "facts": {
   "purpose": "ecommerce",
   "employment_status": "employed",
   "occupation_risk": "standard",
   "adverse_media_non_material": "none",
   "prior_str": "none",
   "residence_country_risk": "standard",
   "nationality_risk": "standard",
   "sow_country_risk": "standard",
   "payment_method": "crypto",
   "product_type": "closed_loop",
   "channel": "face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 4.5,
   "category_scores": {
    "customer": 0.0,
    "geography": 0.0,
    "product_payment": 30.0,
    "channel": 0.0,
    "transactions": 0.0
   },
   "band": "LOW",
   "dd_level": "SDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING"
   ],
   "review_months": 36,
   "missing_factors": [
    "payment_method"
   ],
   "reason_codes": [
    "FACTOR_PURPOSE_LOW",
    "FACTOR_EMPLOYMENT_STATUS_LOW",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_LOW",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "DATA_MISSING_PAYMENT_METHOD",
    "INVALID_VALUE_PAYMENT_METHOD",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_LOW",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_LOW",
    "DD_SDD"
   ]
  }
 },
 {
  "id": "CB-21",
  "title": "Boundary check: score exactly 36.00 is MEDIUM",
  "source": "band boundary Q4",
  "facts": {
   "purpose": "gambling",
   "employment_status": "student",
   "occupation_risk": "high_risk",
   "adverse_media_non_material": "none",
   "prior_str": "one_or_more",
   "residence_country_risk": "higher",
   "nationality_risk": "high_risk_third_country",
   "sow_country_risk": "standard",
   "payment_method": "cash",
   "product_type": "closed_loop",
   "channel": "non_face_to_face",
   "affordability": "not_observed",
   "behaviour_change": "not_observed",
   "high_value_transactions": "not_observed",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 36.0,
   "category_scores": {
    "customer": 60.0,
    "geography": 50.0,
    "product_payment": 60.0,
    "channel": 100.0,
    "transactions": 0.0
   },
   "band": "MEDIUM",
   "dd_level": "CDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE"
   ],
   "review_months": 24,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_MEDIUM",
    "FACTOR_EMPLOYMENT_STATUS_MEDIUM",
    "FACTOR_OCCUPATION_RISK_HIGH",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_LOW",
    "FACTOR_PRIOR_STR_HIGH",
    "FACTOR_RESIDENCE_COUNTRY_RISK_MEDIUM",
    "FACTOR_NATIONALITY_RISK_HIGH",
    "FACTOR_SOW_COUNTRY_RISK_LOW",
    "FACTOR_PAYMENT_METHOD_HIGH",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_LOW",
    "FACTOR_BEHAVIOUR_CHANGE_LOW",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_LOW",
    "BAND_MEDIUM",
    "DD_CDD"
   ]
  }
 },
 {
  "id": "CB-22",
  "title": "Boundary check: score exactly 76.00 is HIGH",
  "source": "band boundary Q4",
  "facts": {
   "purpose": "multipurpose",
   "employment_status": "retired",
   "occupation_risk": "standard",
   "adverse_media_non_material": "single",
   "prior_str": "none",
   "residence_country_risk": "high_risk_third_country",
   "nationality_risk": "standard",
   "sow_country_risk": "higher",
   "payment_method": "bank_transfer",
   "product_type": "open_loop",
   "channel": "non_face_to_face",
   "affordability": "above_limit",
   "behaviour_change": "significant",
   "high_value_transactions": "yes",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 76.0,
   "category_scores": {
    "customer": 47.5,
    "geography": 55.0,
    "product_payment": 40.0,
    "channel": 100.0,
    "transactions": 100.0
   },
   "band": "HIGH",
   "dd_level": "EDD",
   "outcome": "REVIEW_REQUIRED",
   "overrides_hit": [],
   "approvals_required": [
    "MLRO",
    "BOARD"
   ],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE",
    "OBTAIN_SOW_SOF_DOCUMENTS"
   ],
   "review_months": 12,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_HIGH",
    "FACTOR_EMPLOYMENT_STATUS_MEDIUM",
    "FACTOR_OCCUPATION_RISK_LOW",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_MEDIUM",
    "FACTOR_PRIOR_STR_LOW",
    "FACTOR_RESIDENCE_COUNTRY_RISK_HIGH",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_MEDIUM",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_HIGH",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_HIGH",
    "FACTOR_BEHAVIOUR_CHANGE_HIGH",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_HIGH",
    "BAND_HIGH",
    "DD_EDD"
   ]
  }
 },
 {
  "id": "CB-23",
  "title": "Boundary check: score 75.50 stays MEDIUM",
  "source": "band boundary Q4",
  "facts": {
   "purpose": "gambling",
   "employment_status": "self_employed",
   "occupation_risk": "high_risk",
   "adverse_media_non_material": "multiple",
   "prior_str": "one_or_more",
   "residence_country_risk": "high_risk_third_country",
   "nationality_risk": "standard",
   "sow_country_risk": "higher",
   "payment_method": "bank_transfer",
   "product_type": "closed_loop",
   "channel": "non_face_to_face",
   "affordability": "above_limit",
   "behaviour_change": "significant",
   "high_value_transactions": "yes",
   "sanctions_match": "none",
   "pep_status": "none",
   "adverse_media_material": "none",
   "hnwi": false,
   "blacklisted_country_link": false
  },
  "expected": {
   "overall_score": 75.5,
   "category_scores": {
    "customer": 75.0,
    "geography": 55.0,
    "product_payment": 0.0,
    "channel": 100.0,
    "transactions": 100.0
   },
   "band": "MEDIUM",
   "dd_level": "CDD",
   "outcome": "PROCEED",
   "overrides_hit": [],
   "approvals_required": [],
   "required_actions": [
    "IDENTIFY_CUSTOMER",
    "VERIFY_ID",
    "ONGOING_SCREENING",
    "OBTAIN_PURPOSE_AND_NATURE"
   ],
   "review_months": 24,
   "missing_factors": [],
   "reason_codes": [
    "FACTOR_PURPOSE_MEDIUM",
    "FACTOR_EMPLOYMENT_STATUS_MEDIUM",
    "FACTOR_OCCUPATION_RISK_HIGH",
    "FACTOR_ADVERSE_MEDIA_NON_MATERIAL_HIGH",
    "FACTOR_PRIOR_STR_HIGH",
    "FACTOR_RESIDENCE_COUNTRY_RISK_HIGH",
    "FACTOR_NATIONALITY_RISK_LOW",
    "FACTOR_SOW_COUNTRY_RISK_MEDIUM",
    "FACTOR_PAYMENT_METHOD_LOW",
    "FACTOR_PRODUCT_TYPE_LOW",
    "FACTOR_CHANNEL_HIGH",
    "FACTOR_AFFORDABILITY_HIGH",
    "FACTOR_BEHAVIOUR_CHANGE_HIGH",
    "FACTOR_HIGH_VALUE_TRANSACTIONS_HIGH",
    "BAND_MEDIUM",
    "DD_CDD"
   ]
  }
 }
]$casebook$::jsonb);

-- 0. Structure of the seeded template ---------------------------------------
select pg_temp.assert(
  (select engine_kind = 'cra_v2' and status = 'published' and label = 'EU Payments & Gaming CRA — v1 DRAFT' and missing_factor_points = 50
   from public.policy_versions where id = '20000000-0000-0000-0000-000000000020'),
  'seed: Template v1 is a published cra_v2 version labelled "EU Payments & Gaming CRA — v1 DRAFT" in the demo tenant'
);
select pg_temp.assert(
  (select tenant_id from public.policy_versions where id = '20000000-0000-0000-0000-000000000020') = '10000000-0000-0000-0000-000000000004'
  and (select slug from public.tenants where id = '10000000-0000-0000-0000-000000000004') = 'eu-payments-demo',
  'seed: the policy lives in the new tenant EU Payments Demo Ltd. (slug eu-payments-demo)'
);
select pg_temp.assert(
  (select count(*) from public.policy_categories where policy_version_id = '20000000-0000-0000-0000-000000000020') = 5
  and (select count(*) from public.policy_category_factors where policy_version_id = '20000000-0000-0000-0000-000000000020') = 14
  and (select count(*) from public.policy_overrides where policy_version_id = '20000000-0000-0000-0000-000000000020') = 7
  and (select count(*) from public.policy_cra_bands where policy_version_id = '20000000-0000-0000-0000-000000000020') = 3,
  'seed: 5 categories, 14 factors, 7 overrides and 3 bands were loaded from the template JSON'
);
select pg_temp.assert(
  (select engine_kind from public.policy_versions where id = '20000000-0000-0000-0000-000000000010') = 'weighted_v1',
  'existing policy versions keep engine_kind weighted_v1'
);
select pg_temp.assert(
  pg_temp.sqlstate_of($q$update public.policy_versions set engine_kind = 'bogus' where id = '20000000-0000-0000-0000-000000000010'$q$) in ('23514', '23001'),
  'an unknown engine_kind is rejected'
);

-- 1. The casebook: every case must match exactly (jsonb equality of the whole object) --
select pg_temp.assert((select count(*) from cra_casebook) = 24, 'casebook has 24 cases');
do $$
declare
  v_case jsonb;
  v_got jsonb;
begin
  for v_case in select c from cra_casebook order by c ->> 'id' loop
    v_got := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_case -> 'facts');
    if v_got is distinct from (v_case -> 'expected') then
      raise exception 'ASSERTION FAILED: casebook % (%) got % expected %', v_case ->> 'id', v_case ->> 'title', v_got, v_case -> 'expected';
    end if;
    raise notice 'ok - casebook % matches exactly: %', v_case ->> 'id', v_case ->> 'title';
  end loop;
end;
$$;

-- 2. Semantics beyond the casebook --------------------------------------------
do $$
declare
  v_base jsonb := (select c -> 'facts' from cra_casebook where c ->> 'id' = 'CB-01');
  v_absent jsonb;
  v_null jsonb;
  v_r jsonb;
begin
  v_absent := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base - 'purpose');
  v_null := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base || '{"purpose": null}'::jsonb);
  perform pg_temp.assert(v_absent = v_null and v_absent -> 'missing_factors' = '["purpose"]'::jsonb,
    'a JSON null fact counts as absent (same result as the key being missing)');
  perform pg_temp.assert(NOT (v_null -> 'reason_codes') ? 'INVALID_VALUE_PURPOSE',
    'a null fact is missing, not invalid');

  v_r := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base || '{"purpose": 5}'::jsonb);
  perform pg_temp.assert((v_r -> 'reason_codes') ? 'INVALID_VALUE_PURPOSE' and (v_r -> 'reason_codes') ? 'DATA_MISSING_PURPOSE',
    'a non-string value for a mapped factor is missing and invalid');
  v_r := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base || '{"purpose": true}'::jsonb);
  perform pg_temp.assert((v_r -> 'missing_factors') = '["purpose"]'::jsonb, 'a boolean value for a mapped factor is missing and invalid');

  v_r := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base || '{"sanctions_match": ["confirmed"]}'::jsonb);
  perform pg_temp.assert(v_r -> 'overrides_hit' = '[]'::jsonb, 'an array fact never hits an override (exact scalar match only)');

  v_r := app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base || '{"unrelated_fact": "x"}'::jsonb);
  perform pg_temp.assert(v_r = (select c -> 'expected' from cra_casebook where c ->> 'id' = 'CB-01'), 'unknown extra facts are ignored');

  perform pg_temp.assert(
    app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base)
    = app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', v_base),
    'evaluation is deterministic');
  perform pg_temp.assert(
    pg_temp.sqlstate_of($q$select app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', '[]'::jsonb)$q$) = '22023',
    'facts that are not a JSON object raise 22023');
  perform pg_temp.assert(
    (select provolatile from pg_proc where oid = 'app.evaluate_cra(uuid,uuid,jsonb)'::regprocedure) = 's'
    and (select prosecdef from pg_proc where oid = 'app.evaluate_cra(uuid,uuid,jsonb)'::regprocedure),
    'app.evaluate_cra is stable and security definer');
end;
$$;

-- 3. Publish-time validation: one negative per rule, and no partial publish ----
do $$
declare
  v_ok uuid;
  v_bad uuid;
  v_case record;
  v_n int := 100;
  v_result text;
begin
  -- Positive control: an untouched copy publishes.
  v_ok := pg_temp.copy_cra('10000000-0000-0000-0000-000000000004', 2);
  v_result := pg_temp.try_publish(v_ok);
  perform pg_temp.assert(v_result = 'OK', 'an unmodified copy of the template publishes');
  perform pg_temp.assert((select status from public.policy_versions where id = v_ok) = 'published',
    'the published copy has status published');

  for v_case in
    select * from (values
      ('category weights do not sum to 100', $m$update public.policy_categories set weight = 25 where policy_version_id = %L and key = 'customer'$m$),
      ('factor weights in a category do not sum to 100', $m$update public.policy_category_factors set weight = 35 where policy_version_id = %L and factor_key = 'purpose'$m$),
      ('a points map is empty', $m$update public.policy_category_factors set points = '{}'::jsonb where policy_version_id = %L and factor_key = 'purpose'$m$),
      ('a points value is above 100', $m$update public.policy_category_factors set points = '{"ecommerce": 0, "gambling": 150}'::jsonb where policy_version_id = %L and factor_key = 'purpose'$m$),
      ('a points value is negative', $m$update public.policy_category_factors set points = '{"ecommerce": -5}'::jsonb where policy_version_id = %L and factor_key = 'purpose'$m$),
      ('a points value is not a number', $m$update public.policy_category_factors set points = '{"ecommerce": "low"}'::jsonb where policy_version_id = %L and factor_key = 'purpose'$m$),
      ('a points map is not an object', $m$update public.policy_category_factors set points = '[0, 50]'::jsonb where policy_version_id = %L and factor_key = 'purpose'$m$),
      ('bands have a gap', $m$update public.policy_cra_bands set max_score = 30 where policy_version_id = %L and band = 'LOW'$m$),
      ('bands overlap', $m$update public.policy_cra_bands set min_score = 30 where policy_version_id = %L and band = 'MEDIUM'$m$),
      ('bands do not start at 0', $m$update public.policy_cra_bands set min_score = 5 where policy_version_id = %L and band = 'LOW'$m$),
      ('the last band is not inclusive of 100', $m$update public.policy_cra_bands set max_inclusive = false where policy_version_id = %L and band = 'HIGH'$m$),
      ('the last band does not reach 100', $m$update public.policy_cra_bands set max_score = 99 where policy_version_id = %L and band = 'HIGH'$m$),
      ('there is no HIGH band', $m$delete from public.policy_cra_bands where policy_version_id = %L and band = 'HIGH'$m$),
      ('a band lists an unknown approval', $m$update public.policy_cra_bands set approvals = '["CEO"]'::jsonb where policy_version_id = %L and band = 'HIGH'$m$),
      ('an override has an unknown effect', $m$update public.policy_overrides set effect = 'deny' where policy_version_id = %L and code = 'OVR_PEP'$m$),
      ('an override has no match values', $m$update public.policy_overrides set match_values = '[]'::jsonb where policy_version_id = %L and code = 'OVR_HNWI'$m$),
      ('an override lists actions that are not strings', $m$update public.policy_overrides set actions = '[1]'::jsonb where policy_version_id = %L and code = 'OVR_HNWI'$m$),
      ('missing_factor_points is not set', $m$update public.policy_versions set missing_factor_points = null where id = %L$m$),
      ('there are no categories', $m$delete from public.policy_categories where policy_version_id = %L$m$)
    ) as t(label, stmt)
  loop
    v_n := v_n + 1;
    v_bad := pg_temp.copy_cra('10000000-0000-0000-0000-000000000004', v_n);
    execute format(v_case.stmt, v_bad);
    perform pg_temp.assert(pg_temp.try_publish(v_bad) = '22023',
      format('publish is blocked with 22023 when %s', v_case.label));
    perform pg_temp.assert(
      (select status = 'draft' and published_at is null and published_by is null from public.policy_versions where id = v_bad),
      format('no partial publish when %s', v_case.label));
  end loop;
end;
$$;

-- 4. A published cra_v2 policy is immutable (every child, every write) ---------
do $$
declare
  v_t text;
  v_op text;
  v_sql text;
  v_p constant text := '20000000-0000-0000-0000-000000000020';
  v_d constant text := '10000000-0000-0000-0000-000000000004';
begin
  foreach v_t in array array['policy_categories', 'policy_category_factors', 'policy_overrides', 'policy_cra_bands'] loop
    foreach v_op in array array['insert', 'update', 'delete'] loop
      v_sql := case v_t || '/' || v_op
        when 'policy_categories/insert' then format($f$insert into public.policy_categories (tenant_id, policy_version_id, key, label, weight, position) values (%L, %L, 'extra', 'Extra', 1, 99)$f$, v_d, v_p)
        when 'policy_category_factors/insert' then format($f$insert into public.policy_category_factors (tenant_id, policy_version_id, category_key, factor_key, weight, position, points) values (%L, %L, 'channel', 'extra_factor', 1, 99, '{"a": 1}'::jsonb)$f$, v_d, v_p)
        when 'policy_overrides/insert' then format($f$insert into public.policy_overrides (tenant_id, policy_version_id, code, position, fact_key, match_values, effect) values (%L, %L, 'OVR_EXTRA', 99, 'x', '["y"]'::jsonb, 'reject')$f$, v_d, v_p)
        when 'policy_cra_bands/insert' then format($f$insert into public.policy_cra_bands (tenant_id, policy_version_id, band, min_score, max_score, dd_level, review_months) values (%L, %L, 'LOW', 0, 1, 'SDD', 1)$f$, v_d, v_p)
        when 'policy_categories/update' then format('update public.policy_categories set weight = 99 where policy_version_id = %L', v_p)
        when 'policy_category_factors/update' then format($f$update public.policy_category_factors set points = '{"a": 1}'::jsonb where policy_version_id = %L$f$, v_p)
        when 'policy_overrides/update' then format($f$update public.policy_overrides set effect = 'reject' where policy_version_id = %L$f$, v_p)
        when 'policy_cra_bands/update' then format('update public.policy_cra_bands set review_months = 1 where policy_version_id = %L', v_p)
        else format('delete from public.%I where policy_version_id = %L', v_t, v_p)
      end;
      perform pg_temp.assert(pg_temp.sqlstate_of(v_sql) = '23001',
        format('published policy: %s on %s is blocked (23001)', v_op, v_t));
    end loop;
  end loop;
  perform pg_temp.assert(
    pg_temp.sqlstate_of(format($f$update public.policy_versions set label = 'tampered' where id = %L$f$, v_p)) = '23001',
    'published policy: its label cannot be changed');
  perform pg_temp.assert(
    pg_temp.sqlstate_of(format($f$update public.policy_versions set status = 'archived', missing_factor_points = 0 where id = %L$f$, v_p)) = '23001',
    'published policy: archiving cannot also change missing_factor_points');
  perform pg_temp.assert(
    pg_temp.sqlstate_of(format($f$update public.policy_versions set status = 'archived', engine_kind = 'weighted_v1' where id = %L$f$, v_p)) = '23001',
    'published policy: archiving cannot also change engine_kind');
end;
$$;

-- 5. Privileges: authenticated/anon cannot evaluate or write ------------------
select pg_temp.assert(
  not has_function_privilege('authenticated', 'app.evaluate_cra(uuid,uuid,jsonb)', 'execute')
  and not has_function_privilege('anon', 'app.evaluate_cra(uuid,uuid,jsonb)', 'execute'),
  'app.evaluate_cra is not executable by authenticated or anon');
select pg_temp.assert(
  not has_function_privilege('authenticated', 'app.validate_cra_policy_on_publish()', 'execute')
  and not has_function_privilege('authenticated', 'app.cra_string_array_valid(jsonb,text[])', 'execute'),
  'the CRA validator helpers are not executable by authenticated');

insert into public.memberships (tenant_id, user_id, role_key, status) values
  ('10000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000002', 'tenant_admin', 'active'),
  ('10000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000005', 'auditor', 'active');

set role authenticated; set local "request.jwt.claim.role" = 'authenticated'; set local "request.jwt.claim.sub" = '00000000-0000-0000-0000-000000000002';
select pg_temp.assert(
  pg_temp.sqlstate_of($q$select app.evaluate_cra('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000020', '{}'::jsonb)$q$) = '42501',
  'tenant_admin cannot call app.evaluate_cra (42501)');
do $$
declare v_t text; v_op text; v_sql text;
begin
  foreach v_t in array array['policy_categories', 'policy_category_factors', 'policy_overrides', 'policy_cra_bands'] loop
    foreach v_op in array array['insert', 'update', 'delete'] loop
      v_sql := case v_op
        when 'insert' then format('insert into public.%I (tenant_id) values (%L)', v_t, '10000000-0000-0000-0000-000000000004')
        when 'update' then format('update public.%I set created_at = now()', v_t)
        else format('delete from public.%I', v_t)
      end;
      perform pg_temp.assert(pg_temp.sqlstate_of(v_sql) = '42501',
        format('tenant_admin (holds policy.manage) cannot %s %s: no write grant (42501)', v_op, v_t));
    end loop;
  end loop;
end;
$$;
select pg_temp.assert(
  (select count(*) from public.policy_categories where policy_version_id = '20000000-0000-0000-0000-000000000020') = 5
  and (select count(*) from public.policy_category_factors where policy_version_id = '20000000-0000-0000-0000-000000000020') = 14
  and (select count(*) from public.policy_overrides where policy_version_id = '20000000-0000-0000-0000-000000000020') = 7
  and (select count(*) from public.policy_cra_bands where policy_version_id = '20000000-0000-0000-0000-000000000020') = 3,
  'a member with policy.view (tenant_admin) reads the whole CRA structure');
reset role;

set role authenticated; set local "request.jwt.claim.role" = 'authenticated'; set local "request.jwt.claim.sub" = '00000000-0000-0000-0000-000000000005';
select pg_temp.assert(
  (select count(*) from public.policy_cra_bands where policy_version_id = '20000000-0000-0000-0000-000000000020') = 3,
  'auditor (policy.view) reads the CRA bands');
reset role;

set role authenticated; set local "request.jwt.claim.role" = 'authenticated'; set local "request.jwt.claim.sub" = '00000000-0000-0000-0000-000000000006';
select pg_temp.assert(
  (select count(*) from public.policy_categories) = 0 and (select count(*) from public.policy_category_factors) = 0
  and (select count(*) from public.policy_overrides) = 0 and (select count(*) from public.policy_cra_bands) = 0,
  'an outsider tenant admin reads nothing of another tenant''s CRA structure');
reset role;

set role authenticated; set local "request.jwt.claim.role" = 'authenticated'; set local "request.jwt.claim.sub" = '00000000-0000-0000-0000-000000000001';
select pg_temp.assert(
  (select count(*) from public.policy_categories) = 0 and (select count(*) from public.policy_cra_bands) = 0,
  'a platform administrator reads no tenant CRA structure (no operational bypass)');
reset role;

set role anon;
select pg_temp.assert(
  pg_temp.sqlstate_of($q$select count(*) from public.policy_categories$q$) = '42501',
  'anon has no access to the CRA child tables');
reset role;

-- 6. Cross-tenant and non-cra_v2 versions raise 22023 -------------------------
select pg_temp.assert(
  pg_temp.sqlstate_of($q$select app.evaluate_cra('10000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000020', '{}'::jsonb)$q$) = '22023',
  'evaluating another tenant''s cra_v2 version raises 22023');
select pg_temp.assert(
  pg_temp.sqlstate_of($q$select app.evaluate_cra('10000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000010', '{}'::jsonb)$q$) = '22023',
  'evaluating a weighted_v1 version raises 22023');
select pg_temp.assert(
  pg_temp.sqlstate_of($q$select app.evaluate_cra('10000000-0000-0000-0000-000000000004', gen_random_uuid(), '{}'::jsonb)$q$) = '22023',
  'evaluating a nonexistent version raises 22023');

-- 7. Regression: a tenant with a published cra_v2 still evaluates suppliers
-- with its weighted_v1 policy (Amendment 1) ---------------------------------
set role authenticated; set local "request.jwt.claim.role" = 'authenticated'; set local "request.jwt.claim.sub" = '00000000-0000-0000-0000-000000000002';
select public.create_supplier('10000000-0000-0000-0000-000000000003', 'SUP-CRA-COEXIST', 'Coexist Ltd.', 'MT', 'FICT-COEXIST', 'industrial_components', array['MT'], 'CRA coexistence fixture.', 1000, 'EUR', 'assisted', null);
reset role;

do $$
declare
  v_cra uuid := pg_temp.copy_cra('10000000-0000-0000-0000-000000000003', 50);
begin
  perform pg_temp.assert(pg_temp.try_publish(v_cra) = 'OK', 'Meridian publishes a cra_v2 version alongside its weighted_v1 policy');
  perform pg_temp.assert(
    (select count(*) from public.policy_versions where tenant_id = '10000000-0000-0000-0000-000000000003' and status = 'published' and engine_kind = 'cra_v2') = 1
    and (select count(*) from public.policy_versions where tenant_id = '10000000-0000-0000-0000-000000000003' and status = 'published' and engine_kind = 'weighted_v1') = 1
    and (select published_at from public.policy_versions where id = v_cra) > (select published_at from public.policy_versions where id = '20000000-0000-0000-0000-000000000010'),
    'the cra_v2 version is the most recently published policy of the tenant');
end;
$$;

set role authenticated; set local "request.jwt.claim.role" = 'authenticated'; set local "request.jwt.claim.sub" = '00000000-0000-0000-0000-000000000002';
do $$
declare v_result public.evaluations;
begin
  v_result := public.run_supplier_evaluation(
    '10000000-0000-0000-0000-000000000003',
    (select id from public.suppliers where reference = 'SUP-CRA-COEXIST'),
    'd1000000-0000-0000-0000-000000000001');
  perform pg_temp.assert(v_result.status = 'completed' and v_result.policy_version_id = '20000000-0000-0000-0000-000000000010',
    'supplier evaluation still uses the tenant''s weighted_v1 policy when a newer cra_v2 is published');
end;
$$;
reset role;

do $$
begin
  raise notice 'CRA engine v2 verification completed successfully.';
end;
$$;

rollback;
