import { defaultPresentation } from '@/lib/i18n/presentation';
import type {
  DemoAlert,
  DemoCase,
  DemoEvaluation,
  DemoTenant,
} from './types';

export const presentation = defaultPresentation;

export const currentTenant = {
  id: 'ten_helix_commerce',
  name: 'Helix Commerce Ltd.',
  environment: 'Staging',
  policyVersion: 'pol-2026.09.11-v4',
  actor: 'Elena Park',
  operator: 'Jordan Hale',
};

export const demoEmail = 'elena.park@demo.mitiga.local';
export const demoPasswordPlaceholder = 'not-a-real-password';

export const demoEvaluations: DemoEvaluation[] = [
  {
    id: 'ev_10482',
    externalRef: 'EXT-9182',
    subject: 'Customer onboarding 4821',
    tenant: currentTenant.name,
    score: 81,
    band: 'high',
    quality: 'partial',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['DOC_MISMATCH', 'GEO_UNUSUAL', 'DEVICE_REUSE'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T14:08:00.000Z',
    recommendation: 'Request additional evidence before a human decision.',
  },
  {
    id: 'ev_10477',
    externalRef: 'EXT-9104',
    subject: 'Partner onboarding store 17',
    tenant: currentTenant.name,
    score: 48,
    band: 'medium',
    quality: 'complete',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['INCOME_VARIANCE', 'PEP_NEGATIVE'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T13:41:00.000Z',
    recommendation: 'Review the medium band; the contracting company keeps the decision.',
  },
  {
    id: 'ev_10461',
    externalRef: 'EXT-8890',
    subject: 'Profile update 3302',
    tenant: currentTenant.name,
    score: 19,
    band: 'low',
    quality: 'complete',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['PROFILE_STABLE'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T11:22:00.000Z',
    recommendation: 'Follow the published policy acceptance path.',
  },
  {
    id: 'ev_10440',
    externalRef: 'EXT-8744',
    subject: 'Customer onboarding 1093',
    tenant: currentTenant.name,
    score: 72,
    band: 'high',
    quality: 'insufficient',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['MISSING_ADDRESS', 'DOC_EXPIRED'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T09:05:00.000Z',
    recommendation: 'Do not treat missing data as proven risk.',
  },
  {
    id: 'ev_10398',
    externalRef: 'EXT-8511',
    subject: 'Promotional limit 77',
    tenant: currentTenant.name,
    score: 36,
    band: 'medium',
    quality: 'partial',
    policyVersion: 'pol-2026.08.02-v3',
    reasons: ['VELOCITY_BURST'],
    actor: currentTenant.actor,
    evaluatedAt: '2026-09-11T21:18:00.000Z',
    recommendation: 'Keep monitoring; do not change policy from this screen.',
  },
];

export const demoAlerts: DemoAlert[] = [
  {
    id: 'al_2201',
    title: 'Decision webhook delayed',
    severity: 'warning',
    tenant: currentTenant.name,
    subject: 'EXT-9182',
    openedAt: '2026-09-12T14:12:00.000Z',
    slaMinutes: 18,
  },
  {
    id: 'al_2194',
    title: 'Insufficient quality in an onboarding batch',
    severity: 'danger',
    tenant: currentTenant.name,
    subject: 'Batch 12 Sep',
    openedAt: '2026-09-12T10:44:00.000Z',
    slaMinutes: 6,
  },
  {
    id: 'al_2170',
    title: 'Usage near the Growth franchise',
    severity: 'info',
    tenant: currentTenant.name,
    subject: 'Growth plan',
    openedAt: '2026-09-12T08:02:00.000Z',
    slaMinutes: 240,
  },
];

export const demoCases: DemoCase[] = [
  {
    id: 'cs_331',
    subject: 'EXT-9182 — document mismatch',
    tenant: currentTenant.name,
    status: 'waiting_evidence',
    slaDueAt: '2026-09-12T16:00:00.000Z',
    assignee: currentTenant.operator,
    evidenceCount: 2,
    lastNote: 'Waiting for an updated proof of address.',
  },
  {
    id: 'cs_328',
    subject: 'EXT-8744 — incomplete data',
    tenant: currentTenant.name,
    status: 'in_review',
    slaDueAt: '2026-09-12T15:10:00.000Z',
    assignee: currentTenant.operator,
    evidenceCount: 1,
    lastNote: 'High score from missing data; evidence is still partial.',
  },
  {
    id: 'cs_319',
    subject: 'EXT-9104 — medium-band review',
    tenant: currentTenant.name,
    status: 'open',
    slaDueAt: '2026-09-12T17:30:00.000Z',
    assignee: 'Unassigned queue',
    evidenceCount: 3,
    lastNote: 'Ready to claim from the queue.',
  },
  {
    id: 'cs_301',
    subject: 'EXT-7990 — escalated to analyst',
    tenant: currentTenant.name,
    status: 'escalated',
    slaDueAt: '2026-09-12T18:45:00.000Z',
    assignee: 'Samira Okonkwo',
    evidenceCount: 4,
    lastNote: 'Operations handed off; analyst is reviewing DOC_MISMATCH.',
  },
  {
    id: 'cs_274',
    subject: 'EXT-7602 — closed with accept',
    tenant: currentTenant.name,
    status: 'closed',
    slaDueAt: '2026-09-11T19:00:00.000Z',
    assignee: currentTenant.operator,
    evidenceCount: 3,
    lastNote: 'Human decision recorded; policy v3 applied.',
  },
];

export const demoTenants: DemoTenant[] = [
  {
    id: 'ten_helix_commerce',
    name: 'Helix Commerce Ltd.',
    plan: 'Growth',
    health: 'degraded',
    evaluationsToday: 1284,
    webhookFailures: 7,
    consumptionPct: 86,
    billedMinorUnits: 184500,
  },
  {
    id: 'ten_nimbus',
    name: 'Nimbus Payments Inc.',
    plan: 'Pilot',
    health: 'healthy',
    evaluationsToday: 412,
    webhookFailures: 0,
    consumptionPct: 41,
    billedMinorUnits: 49000,
  },
  {
    id: 'ten_cedar',
    name: 'Cedar Marketplaces',
    plan: 'Enterprise',
    health: 'healthy',
    evaluationsToday: 2209,
    webhookFailures: 1,
    consumptionPct: 63,
    billedMinorUnits: 412000,
  },
  {
    id: 'ten_atlas',
    name: 'Atlas Digital Services',
    plan: 'Growth',
    health: 'incident',
    evaluationsToday: 96,
    webhookFailures: 18,
    consumptionPct: 22,
    billedMinorUnits: 24900,
  },
];

export const demoAuditEvents = [
  {
    id: 'aud_9012',
    action: 'policy.publish',
    actor: currentTenant.actor,
    target: 'pol-2026.09.11-v4',
    at: '2026-09-11T18:04:00.000Z',
    correlationId: 'corr_7f3a',
  },
  {
    id: 'aud_9008',
    action: 'case.escalate',
    actor: currentTenant.operator,
    target: 'cs_301',
    at: '2026-09-12T12:16:00.000Z',
    correlationId: 'corr_12bc',
  },
  {
    id: 'aud_8991',
    action: 'tenant.plan.adjust',
    actor: 'platform.ops',
    target: 'ten_helix_commerce',
    at: '2026-09-10T09:40:00.000Z',
    correlationId: 'corr_aa01',
  },
];

export const demoDimensions = [
  { code: 'identity' as const, score: 64, band: 'medium' as const },
  { code: 'fraud' as const, score: 81, band: 'high' as const },
  { code: 'regulatory' as const, score: 44, band: 'medium' as const },
  { code: 'financial' as const, score: 29, band: 'low' as const },
];
