import type {
  DemoAlert,
  DemoCase,
  DemoEvaluation,
  DemoTenant,
} from './types';

export const demoNotice =
  'Protótipo visual com dados fictícios. Nenhuma autenticação, API ou dado de cliente real está conectado.';

export const currentTenant = {
  id: 'ten_arena_ludica',
  name: 'Arena Lúdica S.A.',
  environment: 'Homologação',
  policyVersion: 'pol-2026.09.11-v4',
  actor: 'Helena Duarte',
};

export const demoEvaluations: DemoEvaluation[] = [
  {
    id: 'ev_10482',
    externalRef: 'EXT-9182',
    subject: 'Cadastro jogador 4821',
    tenant: 'Arena Lúdica S.A.',
    score: 81,
    band: 'high',
    quality: 'partial',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['DOC_MISMATCH', 'GEO_UNUSUAL', 'DEVICE_REUSE'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T14:08:00.000Z',
    recommendation: 'Solicitar evidência adicional antes da decisão humana.',
  },
  {
    id: 'ev_10477',
    externalRef: 'EXT-9104',
    subject: 'Onboarding parceiro loja 17',
    tenant: 'Arena Lúdica S.A.',
    score: 48,
    band: 'medium',
    quality: 'complete',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['INCOME_VARIANCE', 'PEP_NEGATIVE'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T13:41:00.000Z',
    recommendation: 'Revisar faixa média; decisão permanece com a contratante.',
  },
  {
    id: 'ev_10461',
    externalRef: 'EXT-8890',
    subject: 'Atualização cadastral 3302',
    tenant: 'Arena Lúdica S.A.',
    score: 19,
    band: 'low',
    quality: 'complete',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['PROFILE_STABLE'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T11:22:00.000Z',
    recommendation: 'Seguir fluxo padrão de aceite da política publicada.',
  },
  {
    id: 'ev_10440',
    externalRef: 'EXT-8744',
    subject: 'Cadastro jogador 1093',
    tenant: 'Arena Lúdica S.A.',
    score: 72,
    band: 'high',
    quality: 'insufficient',
    policyVersion: 'pol-2026.09.11-v4',
    reasons: ['MISSING_ADDRESS', 'DOC_EXPIRED'],
    actor: 'motor.evaluation',
    evaluatedAt: '2026-09-12T09:05:00.000Z',
    recommendation: 'Não tratar ausência de dado como risco comprovado.',
  },
  {
    id: 'ev_10398',
    externalRef: 'EXT-8511',
    subject: 'Limite promocional 77',
    tenant: 'Arena Lúdica S.A.',
    score: 36,
    band: 'medium',
    quality: 'partial',
    policyVersion: 'pol-2026.08.02-v3',
    reasons: ['VELOCITY_BURST'],
    actor: 'Helena Duarte',
    evaluatedAt: '2026-09-11T21:18:00.000Z',
    recommendation: 'Manter monitoramento; não alterar política nesta tela.',
  },
];

export const demoAlerts: DemoAlert[] = [
  {
    id: 'al_2201',
    title: 'Webhook de decisão atrasado',
    severity: 'warning',
    tenant: 'Arena Lúdica S.A.',
    subject: 'EXT-9182',
    openedAt: '2026-09-12T14:12:00.000Z',
    slaMinutes: 18,
  },
  {
    id: 'al_2194',
    title: 'Qualidade insuficiente em lote de onboarding',
    severity: 'danger',
    tenant: 'Arena Lúdica S.A.',
    subject: 'Lote 12/09',
    openedAt: '2026-09-12T10:44:00.000Z',
    slaMinutes: 6,
  },
  {
    id: 'al_2170',
    title: 'Consumo próximo da franquia Growth',
    severity: 'info',
    tenant: 'Arena Lúdica S.A.',
    subject: 'Plano Growth',
    openedAt: '2026-09-12T08:02:00.000Z',
    slaMinutes: 240,
  },
];

export const demoCases: DemoCase[] = [
  {
    id: 'cs_331',
    subject: 'EXT-9182 — divergência documental',
    tenant: 'Arena Lúdica S.A.',
    status: 'waiting_evidence',
    slaDueAt: '2026-09-12T16:00:00.000Z',
    assignee: 'Camila Ribeiro',
    evidenceCount: 2,
    lastNote: 'Aguardando comprovante de residência atualizado.',
  },
  {
    id: 'cs_328',
    subject: 'EXT-8744 — dados incompletos',
    tenant: 'Arena Lúdica S.A.',
    status: 'in_review',
    slaDueAt: '2026-09-12T15:10:00.000Z',
    assignee: 'Camila Ribeiro',
    evidenceCount: 1,
    lastNote: 'Score alto por ausência de dado; evidência ainda parcial.',
  },
  {
    id: 'cs_319',
    subject: 'EXT-9104 — revisão de faixa média',
    tenant: 'Arena Lúdica S.A.',
    status: 'open',
    slaDueAt: '2026-09-12T17:30:00.000Z',
    assignee: 'Fila operação',
    evidenceCount: 3,
    lastNote: 'Pronto para assumir na fila.',
  },
  {
    id: 'cs_301',
    subject: 'EXT-7990 — escalado para analista',
    tenant: 'Arena Lúdica S.A.',
    status: 'escalated',
    slaDueAt: '2026-09-12T18:45:00.000Z',
    assignee: 'Igor Nascimento',
    evidenceCount: 4,
    lastNote: 'Operação encaminhou; analista revisa motivos DOC_MISMATCH.',
  },
  {
    id: 'cs_274',
    subject: 'EXT-7602 — concluído com aceite',
    tenant: 'Arena Lúdica S.A.',
    status: 'closed',
    slaDueAt: '2026-09-11T19:00:00.000Z',
    assignee: 'Camila Ribeiro',
    evidenceCount: 3,
    lastNote: 'Decisão humana registrada; política v3 aplicada.',
  },
];

export const demoTenants: DemoTenant[] = [
  {
    id: 'ten_arena_ludica',
    name: 'Arena Lúdica S.A.',
    plan: 'Growth',
    health: 'degraded',
    evaluationsToday: 1284,
    webhookFailures: 7,
    consumptionPct: 86,
  },
  {
    id: 'ten_nimbus',
    name: 'Nimbus Jogos Ltda.',
    plan: 'Pilot',
    health: 'healthy',
    evaluationsToday: 412,
    webhookFailures: 0,
    consumptionPct: 41,
  },
  {
    id: 'ten_porto',
    name: 'Porto Digital Entretenimento',
    plan: 'Enterprise',
    health: 'healthy',
    evaluationsToday: 2209,
    webhookFailures: 1,
    consumptionPct: 63,
  },
  {
    id: 'ten_atlas',
    name: 'Atlas Recreação Digital',
    plan: 'Growth',
    health: 'incident',
    evaluationsToday: 96,
    webhookFailures: 18,
    consumptionPct: 22,
  },
];

export const demoAuditEvents = [
  {
    id: 'aud_9012',
    action: 'policy.publish',
    actor: 'Helena Duarte',
    target: 'pol-2026.09.11-v4',
    at: '2026-09-11T18:04:00.000Z',
    correlationId: 'corr_7f3a',
  },
  {
    id: 'aud_9008',
    action: 'case.escalate',
    actor: 'Camila Ribeiro',
    target: 'cs_301',
    at: '2026-09-12T12:16:00.000Z',
    correlationId: 'corr_12bc',
  },
  {
    id: 'aud_8991',
    action: 'tenant.plan.adjust',
    actor: 'plataforma.ops',
    target: 'ten_arena_ludica',
    at: '2026-09-10T09:40:00.000Z',
    correlationId: 'corr_aa01',
  },
];

export const demoDimensions = [
  { code: 'identity', label: 'Identidade', score: 64, band: 'medium' as const },
  { code: 'fraud', label: 'Fraude', score: 81, band: 'high' as const },
  { code: 'regulatory', label: 'Regulatório', score: 44, band: 'medium' as const },
  { code: 'credit', label: 'Financeiro', score: 29, band: 'low' as const },
];
